FROM maven:latest AS project_manager
RUN mkdir /app
WORKDIR /app
COPY src pom.xml ./
RUN mvn package -DskipTests=true

FROM eclipse-temurin:latest 
COPY --from=project_manager /app/target/sinta_app-0.0.1-SNAPSHOT.jar .
ENTRYPOINT ["java", "-jar", "sinta_app-0.0.1-SNAPSHOT.jar"]